MyBlog/urls.py
from django.conf.urls import url,include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'',include('blog.urls')),
    url(r'',include('comments.urls')),
]

blog/urls.py
from django.conf.urls import url

from . import  views

#声明此模块属于blog应用
#视图函数命名,防止冲突
app_name = 'blog'

urlpatterns = [
    url(r'^$',views.index, name = 'index'),
    url(r'^post/(?P<pk>[0-9]+)/$',views.detail,name='detail'),
    url(r'^archives/(?P<year>[0-9]{4})/(?P<month>[0-9]{1,2})/$',views.archives,name = 'archives'),
    url(r'^category/(?P<pk>[0-9]+)/$',views.category,name='category'),


]

comments/urls.py
from django.conf.urls import url
from . import views

app_name = 'comments'
urlpatterns = [
    url(r'^comment/post/(?P<post_pk>[0-9]+)/$',views.post_comment,name='post_comment'),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse


class Category(models.Model):

    """
    分类(category)
    """
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name


class Tag(models.Model):
    """
    标签(Tag)
    """
    name = models.CharField(max_length = 100)
    def __str__(self):
        return self.name

class Post(models.Model):
    """
    Post(文章)
    """
    #标题
    title = models.CharField(max_length = 80)

    #文章正文
    body = models.TextField()

    #文章创建时间    文章更新时间
    created_time = models.DateTimeField()
    modified_time = models.DateTimeField()

    #文章摘要  可空
    excerpt = models.CharField(max_length = 200,blank=True)

    category = models.ForeignKey(Category)
    tags = models.ManyToManyField(Tag, blank = True)

    #作者
    author = models.ForeignKey(User)

    #新增博客阅读量
    views = models.PositiveIntegerField(default = 0)

    def increase_views(self):
        self.views = self.views + 1
        self.save(update_fields = ['views'])

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:detail',kwargs={'pk':self.pk})

    class Meta:
        ordering = ['-created_time']

comments/models.py
from django.db import models

class Comment(models.Model):
    #评论用户姓名
    name = models.CharField(max_length=100)
    #评论用户email
    email = models.EmailField(max_length=255)
    #评论时间
    created_time = models.DateTimeField(auto_now_add=True)
    #评论内容
    text = models.TextField()

    post = models.ForeignKey('blog.Post')

    #返回用户的评论
    def __str__(self):
        return self.text[:20]

comments/forms.py
#评论表单  收集用户输入数据到服务器
from django import forms
from .models import Comment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name','email','text']

blog/views.py
import markdown
from django.shortcuts import render,get_object_or_404
from .models import Post,Category
from comments.forms import CommentForm
from django.core.paginator import Paginator,EmptyPage, PageNotAnInteger
def index(request):

    #文章集合 根据创建文章的时间排序
    post_list = Post.objects.all()

    paginator = Paginator(post_list,2)

    page = request.GET.get('page')

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:#用户请求页面不是整数,显示第一页
        posts = paginator.page(1)
    except EmptyPage:     #用户请求页面超过本身页面,显示最后一页
        posts = paginator.page(paginator.num_pages)
    return  render(request,'blog/index.html',context = {'posts' : posts})


#显示文章详细页面
def detail(request,pk):
    post = get_object_or_404(Post,pk=pk)

    #每被阅读一次，阅读量+1
    post.increase_views()

    # 引入markdown
    post.body = markdown.markdown(post.body,
                                  extensions=[
                                      'markdown.extensions.extra',
                                      'markdown.extensions.codehilite',
                                      'markdown.extensions.toc'
                                  ])
    form = CommentForm()
    #获取这篇文章下的全部评论
    comment_list = post.comment_set.all()

    #将文章,表单,评论列表作为变量床给detail.html模板
    context = {
        'post' : post,
        'form':form,
        'comment_list': comment_list
    }
    return render(request,'blog/detail.html',context=context)

#归档
def archives(request,year,month):
    #filter进行过滤
    post_list = Post.objects.filter(created_time__year = year,
                                    created_time__month = month
                                    )
    return render(request,'blog/index.html',context = {'post_list': post_list})

#分类
def category(request,pk):
    cate = get_object_or_404(Category,pk=pk)
    #按照点击的分类名 进入其文章页面
    post_list = Post.objects.filter(category=cate)
    return render(request,'blog/index.html',context={'post_list':post_list})

comments/views.py
from django.shortcuts import render,get_object_or_404,redirect
from blog.models import Post

from .models import Comment
from .forms import CommentForm

def post_comment(request,post_pk):
    #获取被评论的文章
    post = get_object_or_404(Post,pk=post_pk)

    if request.method == 'POST':#用户提交数据
        form = CommentForm(request.POST)

        if form.is_valid():#合法
            comment = form.save(commit=False)

            #将评论和评论文章关联
            comment.post = post
            #保存进数据库
            comment.save()
            #重定向到详情页
            return redirect(post)

        else:

            comment_list = post.comment_set.all()
            context = {'post' : post,
                       'form' : form,
                       'comment_list' : comment_list,
            }
            return render(request,'blog/detail.html',context=context)
    #用户没有提交数据
    return redirect(post)

templates/base.html
{% load staticfiles %}
{% load blog_tags %}
<!DOCTYPE html>
<html>
<head>
    <title>Black &amp; White</title>

    <!-- meta -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- css -->
    <link rel="stylesheet" href="{% static 'blog/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{% static 'blog/css/pace.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/custom.css' %}">
    <link rel="stylesheet" href="{% static 'blog/css/highlights/github.css' %}">


    <!-- js -->
    <script src="{% static 'blog/js/jquery-2.1.3.min.js' %}"></script>
    <script src="{% static 'blog/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'blog/js/pace.min.js' %}"></script>
    <script src="{% static 'blog/js/modernizr.custom.js' %}"></script>
</head>

<body>
<div class="container">
    <header id="site-header">
        <div class="row">
            <div class="col-md-4 col-sm-5 col-xs-8">
                <div class="logo">
                    <h1><a href="{% url 'blog:index' %}"><b>Black</b> &amp; White</a></h1>
                </div>
            </div><!-- col-md-4 -->
            <div class="col-md-8 col-sm-7 col-xs-4">
                <nav class="main-nav" role="navigation">
                    <div class="navbar-header">
                        <button type="button" id="trigger-overlay" class="navbar-toggle">
                            <span class="ion-navicon"></span>
                        </button>
                    </div>

                    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                        <ul class="nav navbar-nav navbar-right">
                            <li class="cl-effect-11"><a href="{% url 'blog:index' %}" data-hover="首页">首页</a></li>
                            <li class="cl-effect-11"><a href="contact.html" data-hover="联系">联系</a></li>
                        </ul>
                    </div><!-- /.navbar-collapse -->
                </nav>
                <div id="header-search-box">
                    <a id="search-menu" href="#"><span id="search-icon" class="ion-ios-search-strong"></span></a>
                    <div id="search-form" class="search-form">
                        <form role="search" method="get" id="searchform" action="#">
                            <input type="search" placeholder="搜索" required>
                            <button type="submit"><span class="ion-ios-search-strong"></span></button>
                        </form>
                    </div>
                </div>
            </div><!-- col-md-8 -->
        </div>
    </header>
</div>
<div class="copyrights">Collect from <a href="http://www.cssmoban.com/">网页模板</a></div>
<div class="copyrights">Modified by <a href="">追梦人物的博客</a></div>

<div class="content-body">
    <div class="container">
        <div class="row">
            <main class="col-md-8">
                {% block main %}
                {% endblock main %}
            </main>

{#        发表的文章       #}
            <aside class="col-md-4">
                {% block toc %}
                {% endblock toc %}
                <div class="widget widget-recent-posts">
                    <h3 class="widget-title">最新文章</h3>
                    {% get_recent_post as recent_post_list %}
                    <ul>
                        {% for post in recent_post_list %}
                        <li>
                            <a href="{{ post.get_absoult_url }}">{{ post.title }}</a>
                        </li>
                       {% empty %}
                        <h3>暂无文章！</h3>
                        {% endfor %}
                    </ul>
                </div>

{#           文章归档      以 年/月 来进行分类   #}
                <div class="widget widget-archives">
                    <h3 class="widget-title">归档</h3>
                    {% archives as date_list %}
                    <ul>
                        {% for date in date_list %}
                        <li>
                            <a href="{% url 'blog:archives' date.year date.month %}">{{ date.year }} 年 {{ date.month }} 月</a>
                        </li>
                        {% empty %}
                        <h3>暂无归档!</h3>
                        {% endfor %}
                    </ul>
                </div>

{#            文章的分类       以标签分类   #}

                <div class="widget widget-category">
                    <h3 class="widget-title">分类</h3>
                    {% get_categories as category_list %}
                    <ul>
                        {% for category in category_list %}
                        <li>
                            <a href="{% url 'blog:category' category.pk %}">{{ category.name }}</a>
                        </li>
                        {% empty %}
                        <h3>暂无分类</h3>
                        {% endfor %}

                    </ul>
                </div>

                <div class="widget widget-tag-cloud">
                    <h3 class="widget-title">标签云</h3>
                    <ul>

                        <li>
                            <a href="#">jQuery</a>
                        </li>
                    </ul>
                </div>
                <div class="rss">
                    <a href=""><span class="ion-social-rss-outline"></span> RSS 订阅</a>
                </div>
            </aside>
        </div>
    </div>
</div>
<footer id="site-footer">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <p class="copyright">&copy 2017 - 采集自<a href="http://www.cssmoban.com/"
                                                        target="_blank" title="模板之家">模板之家</a>
                    - 由<a href="http://zmrenwu.com/" title="网页模板" target="_blank">追梦人物的博客</a>修改
                </p>
            </div>
        </div>
    </div>
</footer>

<!-- Mobile Menu -->
<div class="overlay overlay-hugeinc">
    <button type="button" class="overlay-close"><span class="ion-ios-close-empty"></span></button>
    <nav>
        <ul>
            <li><a href="index.html">首页</a></li>
            <li><a href="full-width.html">博客</a></li>
            <li><a href="about.html">关于</a></li>
            <li><a href="contact.html">联系</a></li>
        </ul>
    </nav>
</div>

<script src="{% static 'blog/js/script.js' %}"></script>

</body>
</html>

templates/blog/detail.html
{% extends 'base.html' %}
{% block main %}

    <article class="post post-1">
        <header class="entry-header">
            <h1 class="entry-title">{{ post.title }}</h1>
            <div class="entry-meta">
                <span class="post-category"><a href="#">{{  post.category.name }}</a></span>
                <span class="post-date"><a href="#"><time class="entry-date"
                                                          datetime="{{ post.created_time }}"></time></a></span>
                <span class="post-author"><a href="#">{{ post.author }}</a></span>
                <span class="comments-link"><a href="#">4 评论</a></span>
                <span class="views-count"><a href="#">{{ post.views }} 阅读</a></span>
            </div>
        </header>
        <div class="entry-content clearfix">
            {{ post.body | safe }}
        </div>
    </article>


    <section class="comment-area" id="comment-area">
        <hr>
        <h3>发表评论</h3>
        <form action="{% url 'comments:post_comment' post.pk %}" method="post" class="comment-form">
            {% csrf_token %}
            <div class="row">
                <div class="col-md-4">
                    <label for="{{ form.name.id_for_label }}">名字：</label>
                    {{ form.name }}
                    {{ form.name.errors }}
                </div>
                <div class="col-md-4">
                    <label for="{{ form.email.id_for_label }}">邮箱：</label>
                    {{ form.email }}
                    {{ form.errors }}
                </div>

                <div class="col-md-12">
                    <label for="{{ form.text.id_for_label }}">评论：</label>
                    {{ form.text }}
                    {{ form.text.errors }}
                    <button type="submit" class="comment-btn">发表</button>
                </div>
            </div>    <!-- row -->
        </form>


        <div class="comment-list-panel">
            {% for com in comment_list %}
            <ul class="comment-list list-unstyled">
                <li class="comment-item">
                    <span class="nickname">{{ com.name }}</span>
                    <time class="submit-date" >{{ com.created_time }}</time>
                    <div class="text">
                        {{ com.text }}
                    </div>
                </li>
                {% empty %}
                暂无评论
            {% endfor %}
            </ul>
        </div>
    </section>
{% endblock main %}




{% block toc %}
    <div class="widget widget-content">
        <h3 class="widget-title">文章目录</h3>
        <ul>
            <li>
                <a href="#">教程特点</a>
            </li>
            <li>
                <a href="#">谁适合这个教程</a>
            </li>
            <li>
                <a href="#">在线预览</a>
            </li>
            <li>
                <a href="#">资源列表</a>
            </li>
            <li>
                <a href="#">获取帮助</a>
            </li>
        </ul>
    </div>
{% endblock toc %}

templates/blog/index.html
{% extends 'base.html' %}

{% block main %}
    {% for post in posts %}
        <article class="post post-1>
            <header class="entry-header">

                <h1 class="entry-title">
                    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
                </h1>
                <div class="entry-meta">
                    <span class="post-category"><a href="{{ post.get_absolute_url }}">{{ post.category.name }}</a></span>
                    <span class="post-date"><a href="{{ post.get_absolute_url }}"><time class="entry-date"
                                                              datetime="{{ post.created_time }}"></time></a></span>
                    <span class="post-author"><a href="{{ post.get_absolute_url }}">{{ post.author }}</a></span>
                    <span class="comments-link"><a href="{{ post.get_absolute_url }}"> 评论</a></span>
                    <span class="views-count"><a href="{{ post.get_absolute_url }}">{{ post.views }} 阅读</a></span>
                </div>
            </header>
            <div class="entry-content clearfix">
                <p>{{ post.body | truncatechars:54 }}</p>

                <div class="read-more cl-effect-14">
                    <a href="{{ post.get_absolute_url }}" class="more-link">继续阅读 <span class="meta-nav">→</span></a>
                </div>
            </div>
        </article>
        {% empty %}
        <div class="no-post"> 暂时还没有文章发布</div>


    {% endfor %}


    <div class="pagination">

        <ul>
            {% if posts_previous %}
            <li><a href="?page={{ posts.previous_page_number }}">上一页</a></li>
            {% endif %}

            <span class="current">
              第 {{ post_list.number }} 页/共 {{ posts.paginator.num_pages }} 页
            </span>

            {% if posts.has_next %}
            <li><a href="?page={{ posts.next_page_number }}">下一页</a></li>
            {% endif %}

        </ul>

    </div>


{% endblock main %}